language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt --upgrade
  - pip install .

notifications:
   email:
      on_success: change
      on_failure: always
