language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install attrs>=19.2.0
  - pip install -r requirements.txt
  - pip install .

notifications:
   email:
      on_success: change
      on_failure: always
